### ISSUE TITLE
Console Error - BlockBreakEvent

### ISSUE THREAD

**Issue by LucidAPs** [AcmeProject/WildernessTp#67] opened 2020-03-24 08:26 UTC
Minecraft: 1.15.2
Tuinity: build 13
Java 11
WildTP : v2.15

https://pastebin.com/raw/vcdQQ1fX

**Comment by RoboMWM** [comment] 2020-03-24 23:07
did I not release wildtp 2.16?

**Comment by RoboMWM** [comment] 2020-03-24 23:07
ok I guess not

**Comment by RoboMWM** [comment] 2020-03-24 23:08
oh it was a different issue tho. This one's a duplicate.

**Comment by RoboMWM** [comment] 2020-03-24 23:10
Duplicate of #53

**Comment by RoboMWM** [comment] 2020-03-24 23:10
Fix by restarting server. See comments for more details.

**Closed by RoboMWM** 2020-03-24 23:10 UTC
