### ISSUE TITLE
Deopped players can't use /wild.

### ISSUE THREAD

**Issue by MajorGilbert** [AcmeProject/WildernessTp#104] opened 2021-06-20 15:33 UTC
Set permission.

_Originally posted by @RoboMWM in https://github.com/AcmeProject/WildernessTp/issues/103#issuecomment-864422248_

This was commented but I don't understand. How do I do this?

**Comment by RoboMWM** [comment] 2021-06-27 04:43
Duplicate of #103

**Closed by RoboMWM** 2021-06-27 04:43 UTC
