### ISSUE TITLE
"wait" value effectively disables plugin for everyone except op players`

### ISSUE THREAD

**Issue by mrcoffee1026** [AcmeProject/WildernessTp#78] opened 2020-06-05 20:41 UTC
Any value over 0 will cause all tp attempts to fail unless the user has permissions to bypass the wait.

v 2.19

enabled the debug spam and sometimes got message "Player must wait more" instead of a tp and sometimes... not even that, it would state the location it had found which was ok to tp to... then do nothing.

**Comment by RoboMWM** [comment] 2020-06-06 04:52
2.19?

That's not what I hear in #77

**Comment by RoboMWM** [comment] 2020-06-06 04:52
Duplicate of #77

**Closed by RoboMWM** 2020-06-06 04:52 UTC
