### ISSUE TITLE
Random teleport destination Y level

### ISSUE THREAD

**Issue by x1p** [AcmeProject/WildernessTp#61] opened 2020-02-16 21:11 UTC
All to often, (lets say around 20%) players are teleported to a level way below the sea level.
So I tried the `dropPlayerFromAbove: true` option.
Even then, I got teleported to level 2 with my head stuck in the bedrock.
Once I got teleported beneath bedrock and "fell of the world"

Why can't I enter a minimum Y level to prevent deep trenches and caves?

Paper 1.15.2 build 105

**Comment by RoboMWM** [comment] 2020-02-17 00:46
Duplicate of #60. This is due to an alleged spigot change.

**Comment by RoboMWM** [comment] 2020-02-17 00:46
Duplicate of #60

**Closed by RoboMWM** 2020-02-17 00:46 UTC

**Comment by RoboMWM** [comment] 2020-02-17 02:08
Actually, I'm guessing your world is a vanilla nether world?

**Comment by x1p** [comment] 2020-02-17 11:25
Overworld actually
