### ISSUE TITLE
AAC compatibility

### ISSUE THREAD

**Issue by LogGits** [AcmeProject/WildernessTp#34] opened 2018-12-02 01:50 UTC
Getting this error:
```
Console 02/12/2018 11:49:03
11:49:03 at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-470]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-470]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@519da3bd
at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
at me.konsolas.aac.bL.b(bL.java:50) ~[?:?]
at me.konsolas.aac.bL.a(bL.java:2) ~[?:?]
at me.konsolas.aac.cL.a(cL.java:153) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1069.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-470]
... 14 more
ERROR 02/12/2018 11:49:03
11:49:03Could not pass event BlurredBlockBreakEvent to AAC v3.6.4
Console 02/12/2018 11:49:03
11:49:03org.bukkit.event.EventException: null
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-470]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-470]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-470]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-470]
at net.poweredbyhate.wildtp.TeleportGoneWild.n0tAGreifClam(TeleportGoneWild.java:255) ~[?:?]
at net.poweredbyhate.wildtp.TeleportGoneWild.chekar(TeleportGoneWild.java:209) ~[?:?]
at net.poweredbyhate.wildtp.TeleportGoneWild$1$1.call(TeleportGoneWild.java:167) ~[?:?]
at net.poweredbyhate.wildtp.TeleportGoneWild$1$1.call(TeleportGoneWild.java:163) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftFuture.run(CraftFuture.java:85) ~[patched_1.13.2.jar:git-Paper-470]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448) ~[patched_1.13.2.jar:git-Paper-470]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-470]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-470]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-470]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-470]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@693ef390
at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
at me.konsolas.aac.bL.b(bL.java:50) ~[?:?]
at me.konsolas.aac.bL.a(bL.java:2) ~[?:?]
at me.konsolas.aac.cL.a(cL.java:153) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1069.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-470]
... 14 more
```
when a user goes through a portal

**Comment by RoboMWM** [comment] 2018-12-02 09:51
Duplicate of #17

**Closed by RoboMWM** 2018-12-02 09:51 UTC
